// Generates supabase/seed.sql from supabase/rubric-v1.json so the SQL editor path and
// the scripted path load byte-identical rubric rows.
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const rubric = JSON.parse(fs.readFileSync(path.join(root, "supabase/rubric-v1.json"), "utf8"));

for (const role of ["pm", "spm"]) {
  const total = rubric.criteria.filter((c) => c.role === role).reduce((s, c) => s + c.weight, 0);
  if (total !== 100) throw new Error(`${role} weights total ${total}, expected 100`);
}

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const rows = rubric.criteria.map((c) => {
  const anchors = {};
  for (const [score, generic] of Object.entries(rubric.scale)) {
    anchors[score] = c.anchors[score] ? `${generic.split(":")[0]}: ${c.anchors[score]}` : generic;
  }
  return `  (${q(c.role)}, ${q(c.key)}, ${q(c.criterion_name)}, ${q(c.short_label)}, ${q(c.description)}, ${c.weight}, ${q(JSON.stringify(anchors))}::jsonb, ${c.position}, ${q(rubric.version)})`;
});

const sql = `-- Generated by scripts/build-seed.mjs from supabase/rubric-v1.json. Do not edit by hand.
-- Rubric ${rubric.version}. Re-running updates descriptions/anchors/weights in place.
insert into public.rubric_criteria (role, key, criterion_name, short_label, description, weight, score_anchors, position, rubric_version)
values
${rows.join(",\n")}
on conflict (role, key, rubric_version) do update set
  criterion_name = excluded.criterion_name,
  short_label    = excluded.short_label,
  description    = excluded.description,
  weight         = excluded.weight,
  score_anchors  = excluded.score_anchors,
  position       = excluded.position,
  active         = true;
`;
fs.writeFileSync(path.join(root, "supabase/seed.sql"), sql);
console.log(`Wrote supabase/seed.sql (${rubric.criteria.length} criteria)`);
